//
//  ProfileViewController.swift
//  testMovies
//
//  Created by Bruno on 9/12/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class ProfileViewController: UIViewController {

    // MARK: - Public properties -

    @IBOutlet weak var labelUserName: UILabel!
    @IBOutlet weak var profileImage: UIImageView!
    var presenter: ProfilePresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        presenter.viewDidLoad()
    }
	
    @IBAction func onTapClose(_ sender: Any) {
        self.dismiss(animated: true)
    }
}

// MARK: - Extensions -

extension ProfileViewController: ProfileViewInterface {
    func setUserName(userName: String) {
        labelUserName.text = userName
    }
    
}
