//
//  ProfileInterfaces.swift
//  testMovies
//
//  Created by Bruno on 9/12/22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ProfileWireframeInterface: WireframeInterface {
}

protocol ProfileViewInterface: ViewInterface {
    func setUserName(userName:String)
}

protocol ProfilePresenterInterface: PresenterInterface {
}
